version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-pgadmin@localhost.localdomain}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - backend_network
  
  baseproject:
    container_name: baseproject
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=dev
    depends_on:
      - postgres
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge