# There is an error/warning in SQLModel like below
#
# ...python3.10/site-packages/sqlmodel/orm/session.py:60: SAWarning: Class SelectOfScalar will not
# make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.
# This can have significant performance implications including some performance degradations in
# comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use
# of the cache key generated by the superclass.  Alternatively, this attribute may be set to False
# which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
#
# and this code fix this warning
from sqlmodel.sql.expression import Select, SelectOfScalar

# Should import all the models with table=True
from .products import Product

# continuing the fix
SelectOfScalar.inherit_cache = True  # type: ignore
Select.inherit_cache = True  # type: ignore
# end of fix
